import type { Book } from "@shared/schema";

// Sample spiritual literature catalog representing books from various sources
export const bookCatalog: Book[] = [
  // Exotic India Books
  {
    id: "ei-001",
    title: "The Brahma Sutras: Text, Word-to-Word Meaning, Translation and Commentary",
    author: "Swami Sivananda",
    description: "A comprehensive study of the Brahma Sutras with Shankaracharya's commentary on Advaita Vedanta philosophy.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/brahma-sutras/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedanta",
  },
  {
    id: "ei-002",
    title: "Vivekachudamani of Sri Shankaracharya",
    author: "Adi Shankaracharya",
    description: "The Crest-Jewel of Discrimination - a foundational text on Advaita Vedanta explaining the path to self-realization.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/vivekachudamani/",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
  },
  {
    id: "ei-003",
    title: "Ashtavakra Gita: The Heart of Awareness",
    author: "Thomas Byrom (translator)",
    description: "A dialogue between sage Ashtavakra and King Janaka on the nature of pure consciousness and non-dual awareness.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/ashtavakra-gita/",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Non-duality",
  },
  {
    id: "ei-004",
    title: "Yoga Vasistha: The Supreme Yoga",
    author: "Swami Venkatesananda",
    description: "Epic philosophical discourse on consciousness, creation, and liberation through the dialogue of Vasistha and Lord Rama.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/yoga-vasistha/",
    price: 1250,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
  },
  {
    id: "ei-005",
    title: "The Upanishads: Breath from the Eternal",
    author: "Swami Prabhavananda",
    description: "Translations of the principal Upanishads exploring the nature of Brahman and Atman.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/upanishads/",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
  },

  // Gita Press Books
  {
    id: "gp-001",
    title: "Srimad Bhagavad Gita (Sadhak Sanjivani)",
    author: "Swami Ramsukhdas",
    description: "The most popular Hindi commentary on the Bhagavad Gita with practical spiritual guidance for seekers.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/sadhak-sanjivani/",
    price: 120,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
  },
  {
    id: "gp-002",
    title: "Shrimad Bhagavad Gita (Tattvavivechani)",
    author: "Jayadayal Goyandka",
    description: "Word-by-word meaning and Hindi translation of the Bhagavad Gita with philosophical commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/bhagavad-gita-tattvavivechani/",
    price: 45,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
  },
  {
    id: "gp-003",
    title: "Srimad Valmiki Ramayana (Two Volumes)",
    author: "Valmiki",
    description: "Complete Sanskrit text with Hindi translation of the original Ramayana epic by Maharshi Valmiki.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/valmiki-ramayana/",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Itihasas",
  },
  {
    id: "gp-004",
    title: "Shri Ramcharitmanas",
    author: "Tulsidas",
    description: "The beloved Hindi retelling of Rama's life by Sant Tulsidas, with commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/ramcharitmanas/",
    price: 180,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Devotional",
  },
  {
    id: "gp-005",
    title: "Kalyan: Upanishad Ank",
    author: "Gita Press Editorial",
    description: "Special edition of Kalyan magazine dedicated to the study of major Upanishads with Hindi explanation.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/kalyan-upanishad/",
    price: 200,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Upanishads",
  },

  // Chaukhamba Books
  {
    id: "ch-001",
    title: "Patanjali Yoga Sutras with Vyasa Bhashya",
    author: "Patanjali",
    description: "The foundational text of Raja Yoga with the classical commentary by Vyasa on the eight limbs of yoga.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/yoga-sutras-vyasa/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
  },
  {
    id: "ch-002",
    title: "Hatha Yoga Pradipika",
    author: "Swatmarama",
    description: "Classical 15th-century manual on Hatha Yoga covering asanas, pranayama, mudras, and bandhas.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/hatha-yoga-pradipika/",
    price: 380,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Hatha Yoga",
  },
  {
    id: "ch-003",
    title: "Charaka Samhita (Complete Set)",
    author: "Charaka",
    description: "Foundational Ayurvedic text covering medicine, philosophy, and the connection between mind and body.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/charaka-samhita/",
    price: 2800,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Ayurveda",
  },
  {
    id: "ch-004",
    title: "Tantra Sara Sangraha",
    author: "Narayana Bhatta",
    description: "Comprehensive compendium of Tantric philosophy, rituals, and practices from Kerala tradition.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/tantra-sara/",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
  },
  {
    id: "ch-005",
    title: "Shiva Samhita",
    author: "Unknown (Traditional)",
    description: "Ancient Sanskrit text on yoga describing philosophy, chakras, kundalini, and advanced practices.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/shiva-samhita/",
    price: 320,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
  },

  // Archive.org Books (Free/Public Domain)
  {
    id: "ar-001",
    title: "The Gospel of Sri Ramakrishna",
    author: "Mahendranath Gupta (M.)",
    description: "Detailed record of conversations with Sri Ramakrishna exploring bhakti, jnana, and the harmony of religions.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/gospelofshrirama00rama",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Bhakti",
  },
  {
    id: "ar-002",
    title: "The Complete Works of Swami Vivekananda",
    author: "Swami Vivekananda",
    description: "Complete collected writings and lectures on Vedanta, Raja Yoga, Karma Yoga, and Indian spirituality.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/completeworksofs00viveuoft",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
  },
  {
    id: "ar-003",
    title: "I Am That: Talks with Sri Nisargadatta Maharaj",
    author: "Nisargadatta Maharaj",
    description: "Dialogues on Advaita Vedanta and the direct path to self-realization through inquiry.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/IAmThat",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Advaita Vedanta",
  },
  {
    id: "ar-004",
    title: "Autobiography of a Yogi",
    author: "Paramahansa Yogananda",
    description: "Spiritual classic describing the author's journey and encounters with saints and yogis of India.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/autobiographyofa00yoga",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
  },
  {
    id: "ar-005",
    title: "The Tibetan Book of the Dead",
    author: "Padmasambhava",
    description: "Guide to the intermediate state between death and rebirth according to Tibetan Buddhist tradition.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/tibetanbookofthedead",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
  },
  {
    id: "ar-006",
    title: "The Dhammapada",
    author: "Buddha (Traditional)",
    description: "Collection of verses attributed to the Buddha, covering ethics, meditation, and wisdom.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/dhammapada",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
  },

  // More Exotic India
  {
    id: "ei-006",
    title: "Mandukya Upanishad with Gaudapada's Karika",
    author: "Gaudapada",
    description: "Profound analysis of consciousness states (waking, dream, deep sleep) and the nature of ultimate reality.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/mandukya-upanishad/",
    price: 575,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
  },
  {
    id: "ei-007",
    title: "Drg-Drsya-Viveka: An Inquiry into the Nature of the Seer and the Seen",
    author: "Adi Shankaracharya (attributed)",
    description: "Short treatise distinguishing the perceiver from the perceived, essential for self-inquiry.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/drg-drsya-viveka/",
    price: 295,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
  },
  {
    id: "ei-008",
    title: "Tripura Rahasya: The Mystery Beyond the Trinity",
    author: "Dattatreya (Traditional)",
    description: "Tantric-Vedantic text on the nature of consciousness and the goddess Tripura as supreme reality.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/tripura-rahasya/",
    price: 425,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra-Vedanta",
  },

  // More Chaukhamba
  {
    id: "ch-006",
    title: "Samkhya Karika of Ishvarakrishna",
    author: "Ishvarakrishna",
    description: "Foundational text of Samkhya philosophy covering the 25 tattvas and the distinction of Purusha and Prakriti.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/samkhya-karika/",
    price: 280,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Samkhya",
  },
  {
    id: "ch-007",
    title: "Nyaya Sutras of Gautama",
    author: "Gautama Rishi",
    description: "Classical text on Indian logic and epistemology covering valid sources of knowledge.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/nyaya-sutras/",
    price: 420,
    currency: "INR",
    isAvailable: false,
    language: "Sanskrit-English",
    category: "Nyaya",
  },
];
