import type { Book } from "@shared/schema";

// Comprehensive spiritual literature catalog from various platforms
// Using Open Library Covers API for real book images: https://covers.openlibrary.org/b/isbn/{ISBN}-M.jpg
export const bookCatalog: Book[] = [
  // ===== EXOTIC INDIA =====
  {
    id: "ei-001",
    title: "The Brahma Sutras: Text, Word-to-Word Meaning, Translation and Commentary",
    author: "Swami Sivananda",
    description: "A comprehensive study of the Brahma Sutras with Shankaracharya's commentary on Advaita Vedanta philosophy.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/brahma-sutras/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8170521122-M.jpg",
    theologicalTags: ["Advaita Vedanta", "Vedanta", "Brahman", "Moksha"],
    keyTopics: ["Brahma Sutras", "Shankaracharya", "Advaita", "Liberation", "Self-realization", "Brahman", "Atman"],
    tableOfContents: ["Introduction to Brahma Sutras", "Samanvaya Adhyaya", "Avirodha Adhyaya", "Sadhana Adhyaya", "Phala Adhyaya"],
  },
  {
    id: "ei-002",
    title: "Vivekachudamani of Sri Shankaracharya",
    author: "Adi Shankaracharya",
    description: "The Crest-Jewel of Discrimination - a foundational text on Advaita Vedanta explaining the path to self-realization through discrimination between the real and unreal.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/vivekachudamani/",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050632-M.jpg",
    theologicalTags: ["Advaita Vedanta", "Self-inquiry", "Discrimination", "Maya"],
    keyTopics: ["Viveka", "Vairagya", "Self-realization", "Maya", "Brahman", "Atman", "Moksha", "Guru"],
    tableOfContents: ["Qualifications of a Seeker", "The Nature of Maya", "The Real and the Unreal", "The Atman", "Liberation"],
  },
  {
    id: "ei-003",
    title: "Ashtavakra Gita: The Heart of Awareness",
    author: "Thomas Byrom (translator)",
    description: "A dialogue between sage Ashtavakra and King Janaka on the nature of pure consciousness and non-dual awareness. One of the most radical Advaita texts.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/ashtavakra-gita/",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Non-duality",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1570628971-M.jpg",
    theologicalTags: ["Advaita", "Non-duality", "Pure Awareness", "Self-knowledge"],
    keyTopics: ["Ashtavakra", "King Janaka", "Non-duality", "Pure consciousness", "Witness awareness", "Self-knowledge"],
    tableOfContents: ["The Vision of Truth", "The Joy of Self-realization", "The Test of True Knowledge", "The Natural State"],
  },
  {
    id: "ei-004",
    title: "Yoga Vasistha: The Supreme Yoga",
    author: "Swami Venkatesananda",
    description: "Epic philosophical discourse on consciousness, creation, and liberation through the dialogue of Vasistha and Lord Rama. Contains stories illustrating Advaita philosophy.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/yoga-vasistha/",
    price: 1250,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120819772-M.jpg",
    theologicalTags: ["Advaita Vedanta", "Jnana Yoga", "Consciousness", "Maya"],
    keyTopics: ["Yoga Vasistha", "Rama", "Sage Vasistha", "Consciousness", "Creation", "Maya", "Liberation", "Stories"],
    tableOfContents: ["Vairagya Prakarana", "Mumukshu Prakarana", "Utpatti Prakarana", "Sthiti Prakarana", "Upashama Prakarana", "Nirvana Prakarana"],
  },
  {
    id: "ei-005",
    title: "The Upanishads: Breath from the Eternal",
    author: "Swami Prabhavananda",
    description: "Translations of the principal Upanishads exploring the nature of Brahman and Atman. Includes Isha, Kena, Katha, Prasna, Mundaka, Mandukya, Taittiriya, Aitareya, Chandogya, Brihadaranyaka.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/upanishads/",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0451628357-M.jpg",
    theologicalTags: ["Upanishads", "Vedanta", "Brahman", "Atman"],
    keyTopics: ["Isha Upanishad", "Kena Upanishad", "Katha Upanishad", "Mundaka Upanishad", "Mandukya Upanishad", "Brahman", "Atman", "Self-knowledge"],
    tableOfContents: ["Isha Upanishad", "Kena Upanishad", "Katha Upanishad", "Prasna Upanishad", "Mundaka Upanishad", "Mandukya Upanishad"],
  },
  {
    id: "ei-006",
    title: "Mandukya Upanishad with Gaudapada's Karika",
    author: "Gaudapada",
    description: "Profound analysis of consciousness states (waking, dream, deep sleep, turiya) and the nature of ultimate reality. Gaudapada's commentary is foundational to Advaita Vedanta.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/mandukya-upanishad/",
    price: 575,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050195-M.jpg",
    theologicalTags: ["Upanishads", "Advaita", "Consciousness", "AUM"],
    keyTopics: ["Mandukya Upanishad", "Gaudapada Karika", "AUM", "Turiya", "Four states of consciousness", "Waking", "Dream", "Deep sleep"],
    tableOfContents: ["Agama Prakarana", "Vaitathya Prakarana", "Advaita Prakarana", "Alatasanti Prakarana"],
  },
  {
    id: "ei-007",
    title: "Drg-Drsya-Viveka: An Inquiry into the Nature of the Seer and the Seen",
    author: "Adi Shankaracharya (attributed)",
    description: "Short treatise distinguishing the perceiver from the perceived, essential for self-inquiry. Analyzes the witness consciousness and meditation practices.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/drg-drsya-viveka/",
    price: 295,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050071-M.jpg",
    theologicalTags: ["Advaita Vedanta", "Self-inquiry", "Witness consciousness"],
    keyTopics: ["Seer and Seen", "Witness consciousness", "Self-inquiry", "Atman", "Meditation", "Discrimination"],
    tableOfContents: ["Analysis of the Seer", "Nature of the Seen", "Witness Consciousness", "Meditation Methods"],
  },
  {
    id: "ei-008",
    title: "Tripura Rahasya: The Mystery Beyond the Trinity",
    author: "Dattatreya (Traditional)",
    description: "Tantric-Vedantic text on the nature of consciousness and the goddess Tripura (Lalita, Tripurasundari) as supreme reality. Contains the Mahavidya teachings on the Divine Mother.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/tripura-rahasya/",
    price: 425,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra-Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8185208514-M.jpg",
    theologicalTags: ["Tantra", "Shakti", "Mahavidya", "Goddess worship", "Advaita"],
    keyTopics: ["Tripura", "Tripurasundari", "Lalita", "Mahavidya", "Shakti", "Divine Mother", "Consciousness", "Tantra"],
    tableOfContents: ["Jnana Khanda", "Charya Khanda", "Mahatmya Khanda"],
  },

  // ===== GITA PRESS (Hindi) =====
  {
    id: "gp-001",
    title: "श्रीमद्भगवद्गीता साधक संजीवनी (Srimad Bhagavad Gita Sadhak Sanjivani)",
    author: "Swami Ramsukhdas",
    description: "The most popular Hindi commentary on the Bhagavad Gita with practical spiritual guidance for seekers.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/sadhak-sanjivani/",
    price: 120,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129304295-M.jpg",
  },
  {
    id: "gp-002",
    title: "श्रीमद्भगवद्गीता तत्त्वविवेचनी (Shrimad Bhagavad Gita Tattvavivechani)",
    author: "Jayadayal Goyandka",
    description: "Word-by-word meaning and Hindi translation of the Bhagavad Gita with philosophical commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/bhagavad-gita-tattvavivechani/",
    price: 45,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300036-M.jpg",
  },
  {
    id: "gp-003",
    title: "श्रीमद्वाल्मीकि रामायण (Srimad Valmiki Ramayana)",
    author: "Valmiki",
    description: "Complete Sanskrit text with Hindi translation of the original Ramayana epic by Maharshi Valmiki.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/valmiki-ramayana/",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Itihasas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300168-M.jpg",
  },
  {
    id: "gp-004",
    title: "श्री रामचरितमानस (Shri Ramcharitmanas)",
    author: "Tulsidas",
    description: "The beloved Hindi retelling of Rama's life by Sant Tulsidas, with commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/ramcharitmanas/",
    price: 180,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Devotional",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300265-M.jpg",
  },
  {
    id: "gp-005",
    title: "कल्याण उपनिषद अंक (Kalyan: Upanishad Ank)",
    author: "Gita Press Editorial",
    description: "Special edition of Kalyan magazine dedicated to the study of major Upanishads with Hindi explanation.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/kalyan-upanishad/",
    price: 200,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Upanishads",
    imageUrl: null,
  },
  {
    id: "gp-006",
    title: "श्री दुर्गा सप्तशती (Shri Durga Saptashati)",
    author: "Ved Vyasa",
    description: "Sacred text containing 700 verses glorifying Goddess Durga with Hindi translation and explanation.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/durga-saptashati/",
    price: 75,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Shakti",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300303-M.jpg",
  },
  {
    id: "gp-007",
    title: "श्रीमद्भागवत महापुराण (Shrimad Bhagavat Mahapurana)",
    author: "Ved Vyasa",
    description: "Complete Hindi translation of the Bhagavata Purana with stories of Lord Krishna and other avatars.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/bhagavat-purana/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Puranas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300370-M.jpg",
  },
  {
    id: "gp-008",
    title: "हनुमान चालीसा (Hanuman Chalisa)",
    author: "Tulsidas",
    description: "The famous 40-verse devotional hymn to Lord Hanuman with meaning and explanation in Hindi.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/hanuman-chalisa/",
    price: 15,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Devotional",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8129300524-M.jpg",
  },

  // ===== CHAUKHAMBA =====
  {
    id: "ch-001",
    title: "Patanjali Yoga Sutras with Vyasa Bhashya",
    author: "Patanjali",
    description: "The foundational text of Raja Yoga with the classical commentary by Vyasa on the eight limbs of yoga.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/yoga-sutras-vyasa/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8121509017-M.jpg",
  },
  {
    id: "ch-002",
    title: "Hatha Yoga Pradipika",
    author: "Swatmarama",
    description: "Classical 15th-century manual on Hatha Yoga covering asanas, pranayama, mudras, and bandhas.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/hatha-yoga-pradipika/",
    price: 380,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Hatha Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8185787387-M.jpg",
  },
  {
    id: "ch-003",
    title: "Charaka Samhita (Complete Set)",
    author: "Charaka",
    description: "Foundational Ayurvedic text covering medicine, philosophy, and the connection between mind and body.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/charaka-samhita/",
    price: 2800,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Ayurveda",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8176370126-M.jpg",
  },
  {
    id: "ch-004",
    title: "Tantra Sara Sangraha",
    author: "Narayana Bhatta",
    description: "Comprehensive compendium of Tantric philosophy, rituals, and practices from Kerala tradition.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/tantra-sara/",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: null,
  },
  {
    id: "ch-005",
    title: "Shiva Samhita",
    author: "Unknown (Traditional)",
    description: "Ancient Sanskrit text on yoga describing philosophy, chakras, kundalini, and advanced practices.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/shiva-samhita/",
    price: 320,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8185787158-M.jpg",
  },

  // ===== ARCHIVE.ORG (Free) =====
  {
    id: "ar-001",
    title: "The Gospel of Sri Ramakrishna",
    author: "Mahendranath Gupta (M.)",
    description: "Detailed record of conversations with Sri Ramakrishna exploring bhakti, jnana, and the harmony of religions.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/gospelofshrirama00rama",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Bhakti",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0911206019-M.jpg",
  },
  {
    id: "ar-002",
    title: "The Complete Works of Swami Vivekananda",
    author: "Swami Vivekananda",
    description: "Complete collected writings and lectures on Vedanta, Raja Yoga, Karma Yoga, and Indian spirituality.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/completeworksofs00viveuoft",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050128-M.jpg",
  },
  {
    id: "ar-003",
    title: "I Am That: Talks with Sri Nisargadatta Maharaj",
    author: "Nisargadatta Maharaj",
    description: "Dialogues on Advaita Vedanta and the direct path to self-realization through inquiry.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/IAmThat",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Advaita Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0893860468-M.jpg",
  },
  {
    id: "ar-004",
    title: "Autobiography of a Yogi",
    author: "Paramahansa Yogananda",
    description: "Spiritual classic describing the author's journey and encounters with saints and yogis of India.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/autobiographyofa00yoga",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0876120796-M.jpg",
  },
  {
    id: "ar-005",
    title: "The Tibetan Book of the Dead",
    author: "Padmasambhava",
    description: "Guide to the intermediate state between death and rebirth according to Tibetan Buddhist tradition.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/tibetanbookofthedead",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0140455264-M.jpg",
  },
  {
    id: "ar-006",
    title: "The Dhammapada",
    author: "Buddha (Traditional)",
    description: "Collection of verses attributed to the Buddha, covering ethics, meditation, and wisdom.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/dhammapada",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0140442847-M.jpg",
  },

  // ===== AMAZON =====
  {
    id: "amz-001",
    title: "The Bhagavad Gita (Penguin Classics)",
    author: "Eknath Easwaran",
    description: "Modern translation with extensive commentary making ancient wisdom accessible to contemporary readers.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1586380192",
    price: 499,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Bhagavad Gita",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1586380192-M.jpg",
  },
  {
    id: "amz-002",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "Guide to spiritual enlightenment through present-moment awareness, influenced by Advaita Vedanta.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1577314808",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Spirituality",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1577314808-M.jpg",
  },
  {
    id: "amz-003",
    title: "Light on Yoga",
    author: "B.K.S. Iyengar",
    description: "The definitive guide to yoga practice with detailed instructions for over 200 asanas.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0805210318",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0805210318-M.jpg",
  },
  {
    id: "amz-004",
    title: "Aghora: At the Left Hand of God",
    author: "Robert E. Svoboda",
    description: "Fascinating account of the Aghori tradition and teachings of Vimalananda.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0914732212",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0914732212-M.jpg",
  },
  {
    id: "amz-005",
    title: "Kundalini: The Evolutionary Energy in Man",
    author: "Gopi Krishna",
    description: "First-hand account of kundalini awakening with scientific and spiritual analysis.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1570622809",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Kundalini",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1570622809-M.jpg",
  },
  {
    id: "amz-006",
    title: "The Upanishads (Eknath Easwaran)",
    author: "Eknath Easwaran",
    description: "Clear and accessible translations of key Upanishads with insightful commentary.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1586380214",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1586380214-M.jpg",
  },
  {
    id: "amz-007",
    title: "Siddhartha",
    author: "Hermann Hesse",
    description: "Novel about spiritual journey inspired by Buddhist and Hindu philosophy.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0553208845",
    price: 199,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Fiction",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0553208845-M.jpg",
  },
  {
    id: "amz-008",
    title: "The Yoga Sutras of Patanjali",
    author: "Sri Swami Satchidananda",
    description: "Popular commentary on Patanjali's Yoga Sutras with practical application.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1938477078",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1938477073-M.jpg",
  },
  {
    id: "amz-009",
    title: "Talks with Sri Ramana Maharshi",
    author: "Sri Ramana Maharshi",
    description: "Collection of dialogues with the great sage of Arunachala on self-inquiry.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/8188018074",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Advaita Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8182880386-M.jpg",
  },
  {
    id: "amz-010",
    title: "The Heart of the Buddha's Teaching",
    author: "Thich Nhat Hanh",
    description: "Introduction to core Buddhist teachings on suffering, mindfulness, and the Noble Eightfold Path.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0767903692",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0767903692-M.jpg",
  },
  {
    id: "amz-011",
    title: "श्रीमद्भगवद्गीता यथारूप (Bhagavad Gita As It Is - Hindi)",
    author: "A.C. Bhaktivedanta Swami Prabhupada",
    description: "Complete Hindi translation with Vaishnava commentary by the founder of ISKCON.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/B07HRMTCHP",
    price: 299,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Bhagavad Gita",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0892131233-M.jpg",
  },
  {
    id: "amz-012",
    title: "Inner Engineering: A Yogi's Guide",
    author: "Sadhguru",
    description: "Modern approach to yoga and inner transformation from the founder of Isha Foundation.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0812997794",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0812997794-M.jpg",
  },
  {
    id: "amz-013",
    title: "Karma: A Yogi's Guide to Crafting Your Destiny",
    author: "Sadhguru",
    description: "Exploration of karma, free will, and how to transcend cyclical patterns.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1984880861",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Philosophy",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1984880861-M.jpg",
  },
  {
    id: "amz-014",
    title: "The Book of Secrets",
    author: "Osho",
    description: "Commentary on Vigyan Bhairav Tantra with 112 meditation techniques.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0312650604",
    price: 599,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0312650604-M.jpg",
  },
  {
    id: "amz-015",
    title: "Apprenticed to a Himalayan Master",
    author: "Sri M",
    description: "Autobiography of spiritual journey and encounter with mysterious Himalayan master.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/8189988727",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8189988727-M.jpg",
  },

  // ===== FLIPKART =====
  {
    id: "fk-001",
    title: "The Complete Book of Yoga",
    author: "Swami Vivekananda",
    description: "Compilation of Vivekananda's works on Raja Yoga, Karma Yoga, Jnana Yoga, and Bhakti Yoga.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/complete-book-yoga/p/itm12345",
    price: 299,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050128-M.jpg",
  },
  {
    id: "fk-002",
    title: "The Science of Pranayama",
    author: "Swami Sivananda",
    description: "Comprehensive guide to pranayama techniques with theoretical and practical aspects.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/science-pranayama/p/itm67890",
    price: 150,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8170520142-M.jpg",
  },
  {
    id: "fk-003",
    title: "Meditation and Its Methods",
    author: "Swami Vivekananda",
    description: "Practical instructions on meditation from the great teacher of Vedanta.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/meditation-methods/p/itm11111",
    price: 125,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Meditation",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050268-M.jpg",
  },
  {
    id: "fk-004",
    title: "Bhaja Govindam",
    author: "Adi Shankaracharya",
    description: "Devotional hymn on the importance of seeking liberation with commentary.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/bhaja-govindam/p/itm22222",
    price: 95,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Devotional",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050578-M.jpg",
  },
  {
    id: "fk-005",
    title: "Atma Bodha: Self-Knowledge",
    author: "Adi Shankaracharya",
    description: "Short treatise on the nature of the Self for beginners in Advaita Vedanta.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/atma-bodha/p/itm33333",
    price: 110,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050101-M.jpg",
  },

  // ===== BOOKISH SANTA =====
  {
    id: "bs-001",
    title: "Kashmir Shaivism: The Secret Supreme",
    author: "Swami Lakshman Joo",
    description: "Introduction to the philosophy of Kashmir Shaivism by the last living master of the tradition.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/kashmir-shaivism",
    price: 750,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Kashmir Shaivism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0914602268-M.jpg",
  },
  {
    id: "bs-002",
    title: "Tantraloka of Abhinavagupta (Vol. 1)",
    author: "Abhinavagupta",
    description: "Encyclopedic work on Tantra by the great philosopher of Kashmir Shaivism.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/tantraloka",
    price: 1200,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120805976-M.jpg",
  },
  {
    id: "bs-003",
    title: "Pratyabhijnahrdayam: The Secret of Self-Recognition",
    author: "Kshemaraja",
    description: "Essential text of Kashmir Shaivism explaining recognition of one's divine nature.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/pratyabhijnahrdayam",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Kashmir Shaivism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120804074-M.jpg",
  },
  {
    id: "bs-004",
    title: "Spanda Karikas",
    author: "Vasugupta",
    description: "Verses on the divine creative pulsation in Kashmir Shaiva philosophy.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/spanda-karikas",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Kashmir Shaivism",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120804716-M.jpg",
  },
  {
    id: "bs-005",
    title: "Vijnanabhairava",
    author: "Unknown (Traditional)",
    description: "Ancient text containing 112 meditation techniques as taught by Shiva to Devi.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/vijnanabhairava",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120808207-M.jpg",
  },

  // ===== VEDIC BOOKS =====
  {
    id: "vb-001",
    title: "The Rig Veda: Complete",
    author: "Ralph T.H. Griffith (translator)",
    description: "Complete English translation of the oldest sacred text of Hinduism.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/rig-veda",
    price: 1800,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0893144002-M.jpg",
  },
  {
    id: "vb-002",
    title: "Sama Veda: The Veda of Melodies",
    author: "Ralph T.H. Griffith (translator)",
    description: "Translation of the Sama Veda containing the melodic hymns of ancient India.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/sama-veda",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8121500516-M.jpg",
  },
  {
    id: "vb-003",
    title: "Yajur Veda",
    author: "Devi Chand (translator)",
    description: "Translation of the Yajur Veda containing sacrificial formulas and rituals.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/yajur-veda",
    price: 750,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8121500524-M.jpg",
  },
  {
    id: "vb-004",
    title: "Atharva Veda",
    author: "Ralph T.H. Griffith (translator)",
    description: "Translation of the fourth Veda containing hymns for everyday rituals.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/atharva-veda",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedas",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8121500532-M.jpg",
  },
  {
    id: "vb-005",
    title: "The Principal Upanishads",
    author: "S. Radhakrishnan",
    description: "Scholarly translation and commentary on major Upanishads by the philosopher-president.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/principal-upanishads",
    price: 950,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8172231245-M.jpg",
  },

  // ===== MLBD (Motilal Banarsidass) =====
  {
    id: "mlbd-001",
    title: "A History of Indian Philosophy (5 Vols)",
    author: "Surendranath Dasgupta",
    description: "Magnum opus covering the entire spectrum of Indian philosophical thought.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/history-indian-philosophy",
    price: 4500,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Philosophy",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120804120-M.jpg",
  },
  {
    id: "mlbd-002",
    title: "The Philosophy of the Upanishads",
    author: "Paul Deussen",
    description: "Classic German scholarly analysis of Upanishadic philosophy translated to English.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/philosophy-upanishads",
    price: 695,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120806573-M.jpg",
  },
  {
    id: "mlbd-003",
    title: "Brahma-Sutra-Bhasya of Shankaracharya",
    author: "Swami Gambhirananda (translator)",
    description: "Complete English translation of Shankara's commentary on the Brahma Sutras.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/brahma-sutra-bhasya",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8175050632-M.jpg",
  },
  {
    id: "mlbd-004",
    title: "The Vedanta Sutras with Commentary by Ramanuja",
    author: "George Thibaut (translator)",
    description: "Sri Bhasya: Ramanuja's Vishishtadvaita commentary on the Brahma Sutras.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/vedanta-sutras-ramanuja",
    price: 750,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120801261-M.jpg",
  },
  {
    id: "mlbd-005",
    title: "Natyashastra of Bharatamuni (4 Vols)",
    author: "Bharata Muni",
    description: "Ancient treatise on dramaturgy, dance, music, and aesthetics.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/natyashastra",
    price: 3200,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Arts",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120805402-M.jpg",
  },
  {
    id: "mlbd-006",
    title: "Arthashastra of Kautilya",
    author: "Kautilya (Chanakya)",
    description: "Ancient Indian treatise on statecraft, economics, and military strategy.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/arthashastra",
    price: 595,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Political Science",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0140446036-M.jpg",
  },
  {
    id: "mlbd-007",
    title: "Panchatantra",
    author: "Vishnu Sharma",
    description: "Collection of ancient Indian fables teaching wisdom through animal stories.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/panchatantra",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Literature",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0140455035-M.jpg",
  },
  {
    id: "mlbd-008",
    title: "The Samkhya Philosophy",
    author: "S.S. Suryanarayana Sastri",
    description: "Detailed study of Samkhya system with Samkhya Karika and commentary.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/samkhya-philosophy",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Philosophy",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120804392-M.jpg",
  },

  // ===== SHAKTA/MAHAVIDYA TEXTS =====
  {
    id: "ei-009",
    title: "The Ten Mahavidyas: Tantric Visions of the Divine Feminine",
    author: "David Kinsley",
    description: "Comprehensive study of the Ten Mahavidyas (Great Wisdom Goddesses) including Kali, Tara, Tripurasundari, Bhuvaneshvari, Chinnamasta, Bhairavi, Dhumavati, Bagalamukhi, Matangi, and Kamala. Examines iconography, mythology, and worship practices.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/ten-mahavidyas/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120817818-M.jpg",
    theologicalTags: ["Mahavidya", "Shakti", "Tantra", "Goddess worship", "Divine Feminine"],
    keyTopics: ["Ten Mahavidyas", "Kali", "Tara", "Tripurasundari", "Bhuvaneshvari", "Chinnamasta", "Bhairavi", "Dhumavati", "Bagalamukhi", "Matangi", "Kamala", "Tantric goddesses"],
    tableOfContents: ["Introduction to the Mahavidyas", "Kali - The Black Goddess", "Tara - The Saving Goddess", "Tripurasundari - Beauty of the Three Worlds", "Bhuvaneshvari - Queen of the Universe", "Chinnamasta - The Self-Decapitated Goddess", "Bhairavi - The Fierce One", "Dhumavati - The Widow", "Bagalamukhi - The Paralyzer", "Matangi - The Outcaste", "Kamala - The Lotus Goddess"],
  },
  {
    id: "ei-010",
    title: "Chinnamasta: The Aweful Buddhist and Hindu Tantric Goddess",
    author: "Elisabeth Anne Benard",
    description: "Definitive scholarly study of Chinnamasta, the self-decapitated goddess who drinks her own blood. Explores her origins in both Hindu and Buddhist Tantra, iconography, rituals, and symbolism of self-sacrifice and transcendence.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/chinnamasta/",
    price: 695,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120817478-M.jpg",
    theologicalTags: ["Chinnamasta", "Mahavidya", "Buddhist Tantra", "Hindu Tantra", "Shakti"],
    keyTopics: ["Chinnamasta", "Mahavidya", "Self-decapitation", "Tantric goddess", "Vajrayogini", "Self-sacrifice", "Transcendence", "Buddhist Tantra"],
    tableOfContents: ["Origins of Chinnamasta", "Chinnamasta in Hindu Tantra", "Chinnamasta in Buddhist Tantra", "Iconography and Symbolism", "Ritual Worship", "Philosophical Significance"],
  },
  {
    id: "amz-016",
    title: "Shakti and Shakta: Essays on the Shakta Tantrashastra",
    author: "Sir John Woodroffe (Arthur Avalon)",
    description: "Classic text on Shakta Tantra explaining the worship of Divine Mother, kundalini, chakras, mantras, and tantric philosophy. Essential reading for understanding Shakti worship.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1596057947",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/1596057947-M.jpg",
    theologicalTags: ["Shakta", "Tantra", "Kundalini", "Shakti", "Divine Mother"],
    keyTopics: ["Shakti", "Shakta Tantra", "Kundalini", "Chakras", "Mantras", "Divine Mother", "Tantric philosophy", "Goddess worship"],
    tableOfContents: ["Shakta Darshana", "Shakti as Conscious Energy", "The Garland of Letters", "Kundalini Shakti", "The Six Centres", "Shakti Puja"],
  },
  {
    id: "bs-006",
    title: "Tantric Visions of the Divine Feminine: The Ten Mahavidyas",
    author: "David Kinsley",
    description: "Explores the ten goddess forms known as Mahavidyas - Kali, Tara, Tripurasundari, Bhuvaneshvari, Chinnamasta, Bhairavi, Dhumavati, Bagalamukhi, Matangi, and Kamala.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/ten-mahavidyas",
    price: 750,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/0520204999-M.jpg",
    theologicalTags: ["Mahavidya", "Shakti", "Tantra", "Divine Feminine", "Goddess"],
    keyTopics: ["Mahavidyas", "Kali", "Tara", "Chinnamasta", "Dhumavati", "Bagalamukhi", "Tantric goddesses", "Divine Feminine"],
    tableOfContents: ["The Mahavidya Tradition", "Kali", "Tara", "Chinnamasta", "Other Mahavidyas"],
  },
  {
    id: "mlbd-009",
    title: "Saundaryalahari of Shankaracharya",
    author: "Nataraja Guru",
    description: "The 'Waves of Beauty' - Shankaracharya's devotional hymn to the Divine Mother with 100 verses describing Shakti's glory, beauty, and power. Contains tantric symbolism and mantra applications.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/saundaryalahari",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Shakti",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120807929-M.jpg",
    theologicalTags: ["Shakti", "Shakta", "Devi", "Kundalini", "Sri Vidya"],
    keyTopics: ["Saundaryalahari", "Divine Mother", "Sri Vidya", "Kundalini", "Chakras", "Tantric mantras", "Devi worship"],
    tableOfContents: ["Ananda Lahari (Waves of Bliss)", "Saundarya Lahari (Waves of Beauty)"],
  },
  {
    id: "ch-006",
    title: "Tantrasara of Abhinavagupta",
    author: "Abhinavagupta",
    description: "Essence of Tantra by the great master of Kashmir Shaivism. Covers Shiva-Shakti philosophy, mantras, mudras, chakras, and advanced tantric practices.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/tantrasara/",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: "https://covers.openlibrary.org/b/isbn/8120806999-M.jpg",
    theologicalTags: ["Kashmir Shaivism", "Tantra", "Shiva-Shakti", "Kundalini"],
    keyTopics: ["Tantrasara", "Abhinavagupta", "Kashmir Shaivism", "Shiva-Shakti", "Mantras", "Mudras", "Chakras", "Kundalini"],
    tableOfContents: ["The Nature of Reality", "The Path of Knowledge", "Mantra Science", "Kundalini Yoga", "Liberation"],
  },
];
