import type { Book } from "@shared/schema";

// Comprehensive spiritual literature catalog from various platforms
export const bookCatalog: Book[] = [
  // ===== EXOTIC INDIA =====
  {
    id: "ei-001",
    title: "The Brahma Sutras: Text, Word-to-Word Meaning, Translation and Commentary",
    author: "Swami Sivananda",
    description: "A comprehensive study of the Brahma Sutras with Shankaracharya's commentary on Advaita Vedanta philosophy.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/brahma-sutras/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "ei-002",
    title: "Vivekachudamani of Sri Shankaracharya",
    author: "Adi Shankaracharya",
    description: "The Crest-Jewel of Discrimination - a foundational text on Advaita Vedanta explaining the path to self-realization.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/vivekachudamani/",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },
  {
    id: "ei-003",
    title: "Ashtavakra Gita: The Heart of Awareness",
    author: "Thomas Byrom (translator)",
    description: "A dialogue between sage Ashtavakra and King Janaka on the nature of pure consciousness and non-dual awareness.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/ashtavakra-gita/",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Non-duality",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },
  {
    id: "ei-004",
    title: "Yoga Vasistha: The Supreme Yoga",
    author: "Swami Venkatesananda",
    description: "Epic philosophical discourse on consciousness, creation, and liberation through the dialogue of Vasistha and Lord Rama.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/yoga-vasistha/",
    price: 1250,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  },
  {
    id: "ei-005",
    title: "The Upanishads: Breath from the Eternal",
    author: "Swami Prabhavananda",
    description: "Translations of the principal Upanishads exploring the nature of Brahman and Atman.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/upanishads/",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  },
  {
    id: "ei-006",
    title: "Mandukya Upanishad with Gaudapada's Karika",
    author: "Gaudapada",
    description: "Profound analysis of consciousness states (waking, dream, deep sleep) and the nature of ultimate reality.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/mandukya-upanishad/",
    price: 575,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=400&fit=crop",
  },
  {
    id: "ei-007",
    title: "Drg-Drsya-Viveka: An Inquiry into the Nature of the Seer and the Seen",
    author: "Adi Shankaracharya (attributed)",
    description: "Short treatise distinguishing the perceiver from the perceived, essential for self-inquiry.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/drg-drsya-viveka/",
    price: 295,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Advaita Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
  },
  {
    id: "ei-008",
    title: "Tripura Rahasya: The Mystery Beyond the Trinity",
    author: "Dattatreya (Traditional)",
    description: "Tantric-Vedantic text on the nature of consciousness and the goddess Tripura as supreme reality.",
    source: "exotic_india",
    sourceUrl: "https://www.exoticindiaart.com/book/details/tripura-rahasya/",
    price: 425,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra-Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },

  // ===== GITA PRESS (Hindi) =====
  {
    id: "gp-001",
    title: "श्रीमद्भगवद्गीता साधक संजीवनी (Srimad Bhagavad Gita Sadhak Sanjivani)",
    author: "Swami Ramsukhdas",
    description: "The most popular Hindi commentary on the Bhagavad Gita with practical spiritual guidance for seekers.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/sadhak-sanjivani/",
    price: 120,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },
  {
    id: "gp-002",
    title: "श्रीमद्भगवद्गीता तत्त्वविवेचनी (Shrimad Bhagavad Gita Tattvavivechani)",
    author: "Jayadayal Goyandka",
    description: "Word-by-word meaning and Hindi translation of the Bhagavad Gita with philosophical commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/bhagavad-gita-tattvavivechani/",
    price: 45,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Bhagavad Gita",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },
  {
    id: "gp-003",
    title: "श्रीमद्वाल्मीकि रामायण (Srimad Valmiki Ramayana)",
    author: "Valmiki",
    description: "Complete Sanskrit text with Hindi translation of the original Ramayana epic by Maharshi Valmiki.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/valmiki-ramayana/",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Itihasas",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  },
  {
    id: "gp-004",
    title: "श्री रामचरितमानस (Shri Ramcharitmanas)",
    author: "Tulsidas",
    description: "The beloved Hindi retelling of Rama's life by Sant Tulsidas, with commentary.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/ramcharitmanas/",
    price: 180,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Devotional",
    imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=400&fit=crop",
  },
  {
    id: "gp-005",
    title: "कल्याण उपनिषद अंक (Kalyan: Upanishad Ank)",
    author: "Gita Press Editorial",
    description: "Special edition of Kalyan magazine dedicated to the study of major Upanishads with Hindi explanation.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/kalyan-upanishad/",
    price: 200,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&h=400&fit=crop",
  },
  {
    id: "gp-006",
    title: "श्री दुर्गा सप्तशती (Shri Durga Saptashati)",
    author: "Ved Vyasa",
    description: "Sacred text containing 700 verses glorifying Goddess Durga with Hindi translation and explanation.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/durga-saptashati/",
    price: 75,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Shakti",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "gp-007",
    title: "श्रीमद्भागवत महापुराण (Shrimad Bhagavat Mahapurana)",
    author: "Ved Vyasa",
    description: "Complete Hindi translation of the Bhagavata Purana with stories of Lord Krishna and other avatars.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/bhagavat-purana/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Hindi-Sanskrit",
    category: "Puranas",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },
  {
    id: "gp-008",
    title: "हनुमान चालीसा (Hanuman Chalisa)",
    author: "Tulsidas",
    description: "The famous 40-verse devotional hymn to Lord Hanuman with meaning and explanation in Hindi.",
    source: "gita_press",
    sourceUrl: "https://gitapress.org/product/hanuman-chalisa/",
    price: 15,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Devotional",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },

  // ===== CHAUKHAMBA =====
  {
    id: "ch-001",
    title: "Patanjali Yoga Sutras with Vyasa Bhashya",
    author: "Patanjali",
    description: "The foundational text of Raja Yoga with the classical commentary by Vyasa on the eight limbs of yoga.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/yoga-sutras-vyasa/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },
  {
    id: "ch-002",
    title: "Hatha Yoga Pradipika",
    author: "Swatmarama",
    description: "Classical 15th-century manual on Hatha Yoga covering asanas, pranayama, mudras, and bandhas.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/hatha-yoga-pradipika/",
    price: 380,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Hatha Yoga",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },
  {
    id: "ch-003",
    title: "Charaka Samhita (Complete Set)",
    author: "Charaka",
    description: "Foundational Ayurvedic text covering medicine, philosophy, and the connection between mind and body.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/charaka-samhita/",
    price: 2800,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Ayurveda",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },
  {
    id: "ch-004",
    title: "Tantra Sara Sangraha",
    author: "Narayana Bhatta",
    description: "Comprehensive compendium of Tantric philosophy, rituals, and practices from Kerala tradition.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/tantra-sara/",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  },
  {
    id: "ch-005",
    title: "Shiva Samhita",
    author: "Unknown (Traditional)",
    description: "Ancient Sanskrit text on yoga describing philosophy, chakras, kundalini, and advanced practices.",
    source: "chaukhamba",
    sourceUrl: "https://chaukhamba.com/product/shiva-samhita/",
    price: 320,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=400&fit=crop",
  },

  // ===== ARCHIVE.ORG (Free) =====
  {
    id: "ar-001",
    title: "The Gospel of Sri Ramakrishna",
    author: "Mahendranath Gupta (M.)",
    description: "Detailed record of conversations with Sri Ramakrishna exploring bhakti, jnana, and the harmony of religions.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/gospelofshrirama00rama",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Bhakti",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  },
  {
    id: "ar-002",
    title: "The Complete Works of Swami Vivekananda",
    author: "Swami Vivekananda",
    description: "Complete collected writings and lectures on Vedanta, Raja Yoga, Karma Yoga, and Indian spirituality.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/completeworksofs00viveuoft",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=400&fit=crop",
  },
  {
    id: "ar-003",
    title: "I Am That: Talks with Sri Nisargadatta Maharaj",
    author: "Nisargadatta Maharaj",
    description: "Dialogues on Advaita Vedanta and the direct path to self-realization through inquiry.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/IAmThat",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Advaita Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
  },
  {
    id: "ar-004",
    title: "Autobiography of a Yogi",
    author: "Paramahansa Yogananda",
    description: "Spiritual classic describing the author's journey and encounters with saints and yogis of India.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/autobiographyofa00yoga",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },
  {
    id: "ar-005",
    title: "The Tibetan Book of the Dead",
    author: "Padmasambhava",
    description: "Guide to the intermediate state between death and rebirth according to Tibetan Buddhist tradition.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/tibetanbookofthedead",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },
  {
    id: "ar-006",
    title: "The Dhammapada",
    author: "Buddha (Traditional)",
    description: "Collection of verses attributed to the Buddha, covering ethics, meditation, and wisdom.",
    source: "archive_org",
    sourceUrl: "https://archive.org/details/dhammapada",
    price: null,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },

  // ===== AMAZON =====
  {
    id: "amz-001",
    title: "The Bhagavad Gita (Penguin Classics)",
    author: "Eknath Easwaran",
    description: "Modern translation with extensive commentary making ancient wisdom accessible to contemporary readers.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1586380192",
    price: 499,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Bhagavad Gita",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "amz-002",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "Guide to spiritual enlightenment through present-moment awareness, influenced by Advaita Vedanta.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1577314808",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Spirituality",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },
  {
    id: "amz-003",
    title: "Light on Yoga",
    author: "B.K.S. Iyengar",
    description: "The definitive guide to yoga practice with detailed instructions for over 200 asanas.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0805210318",
    price: 650,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },
  {
    id: "amz-004",
    title: "Aghora: At the Left Hand of God",
    author: "Robert E. Svoboda",
    description: "Fascinating account of the Aghori tradition and teachings of Vimalananda.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0914732212",
    price: 495,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  },
  {
    id: "amz-005",
    title: "Kundalini: The Evolutionary Energy in Man",
    author: "Gopi Krishna",
    description: "First-hand account of kundalini awakening with scientific and spiritual analysis.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1570622809",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Kundalini",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  },
  {
    id: "amz-006",
    title: "The Upanishads (Eknath Easwaran)",
    author: "Eknath Easwaran",
    description: "Clear and accessible translations of key Upanishads with insightful commentary.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1586380214",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=400&fit=crop",
  },
  {
    id: "amz-007",
    title: "Siddhartha",
    author: "Hermann Hesse",
    description: "Novel about spiritual journey inspired by Buddhist and Hindu philosophy.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0553208845",
    price: 199,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Fiction",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
  },
  {
    id: "amz-008",
    title: "The Yoga Sutras of Patanjali",
    author: "Sri Swami Satchidananda",
    description: "Popular commentary on Patanjali's Yoga Sutras with practical application.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1938477078",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },
  {
    id: "amz-009",
    title: "Talks with Sri Ramana Maharshi",
    author: "Sri Ramana Maharshi",
    description: "Collection of dialogues with the great sage of Arunachala on self-inquiry.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/8188018074",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Advaita Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },
  {
    id: "amz-010",
    title: "The Heart of the Buddha's Teaching",
    author: "Thich Nhat Hanh",
    description: "Introduction to core Buddhist teachings on suffering, mindfulness, and the Noble Eightfold Path.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0767903692",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Buddhism",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },
  {
    id: "amz-011",
    title: "श्रीमद्भगवद्गीता यथारूप (Bhagavad Gita As It Is - Hindi)",
    author: "A.C. Bhaktivedanta Swami Prabhupada",
    description: "Complete Hindi translation with Vaishnava commentary by the founder of ISKCON.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/B07HRMTCHP",
    price: 299,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Bhagavad Gita",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  },
  {
    id: "amz-012",
    title: "Inner Engineering: A Yogi's Guide",
    author: "Sadhguru",
    description: "Modern approach to yoga and inner transformation from the founder of Isha Foundation.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0812997794",
    price: 399,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=400&fit=crop",
  },
  {
    id: "amz-013",
    title: "Karma: A Yogi's Guide to Crafting Your Destiny",
    author: "Sadhguru",
    description: "Exploration of karma, free will, and how to transcend cyclical patterns.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/1984880861",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Philosophy",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&h=400&fit=crop",
  },
  {
    id: "amz-014",
    title: "The Book of Secrets",
    author: "Osho",
    description: "Commentary on Vigyan Bhairav Tantra with 112 meditation techniques.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/0312650604",
    price: 599,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "amz-015",
    title: "Apprenticed to a Himalayan Master",
    author: "Sri M",
    description: "Autobiography of spiritual journey and encounter with mysterious Himalayan master.",
    source: "amazon",
    sourceUrl: "https://www.amazon.in/dp/8189988727",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },

  // ===== FLIPKART =====
  {
    id: "fk-001",
    title: "The Complete Book of Yoga",
    author: "Swami Vivekananda",
    description: "Compilation of Vivekananda's works on Raja Yoga, Karma Yoga, Jnana Yoga, and Bhakti Yoga.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/complete-book-yoga/p/itm123",
    price: 299,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },
  {
    id: "fk-002",
    title: "Chanakya Neeti (Hindi)",
    author: "Chanakya",
    description: "Ancient wisdom on politics, ethics, and practical life from the master strategist.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/chanakya-neeti-hindi/p/itm456",
    price: 150,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Philosophy",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  },
  {
    id: "fk-003",
    title: "योग वशिष्ठ सार (Yoga Vasishtha Sara)",
    author: "Valmiki",
    description: "Condensed Hindi version of the philosophical dialogue between Vasishtha and Rama.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/yoga-vasishtha-sara/p/itm789",
    price: 195,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Vedanta",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  },
  {
    id: "fk-004",
    title: "Meditation and Mantras",
    author: "Swami Vishnu-Devananda",
    description: "Comprehensive guide to meditation techniques and the power of mantras.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/meditation-mantras/p/itm101",
    price: 425,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Meditation",
    imageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=400&fit=crop",
  },
  {
    id: "fk-005",
    title: "Swami and Friends (R.K. Narayan)",
    author: "R.K. Narayan",
    description: "Classic Indian fiction with subtle spiritual undertones about life in Malgudi.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/swami-friends/p/itm202",
    price: 175,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Fiction",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
  },
  {
    id: "fk-006",
    title: "गायत्री महाविद्या (Gayatri Mahavidya)",
    author: "Pt. Shriram Sharma Acharya",
    description: "Comprehensive study of Gayatri mantra and its spiritual significance.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/gayatri-mahavidya/p/itm303",
    price: 250,
    currency: "INR",
    isAvailable: true,
    language: "Hindi",
    category: "Mantra",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },
  {
    id: "fk-007",
    title: "Living with the Himalayan Masters",
    author: "Swami Rama",
    description: "Stories and teachings from encounters with Himalayan sages.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/living-himalayan-masters/p/itm404",
    price: 350,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Autobiography",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },
  {
    id: "fk-008",
    title: "The Science of Pranayama",
    author: "Swami Sivananda",
    description: "Detailed guide to breathing techniques and their spiritual effects.",
    source: "flipkart",
    sourceUrl: "https://www.flipkart.com/science-pranayama/p/itm505",
    price: 175,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Yoga",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },

  // ===== VEDIC BOOKS =====
  {
    id: "vb-001",
    title: "The Vedas: Complete Set with Commentary",
    author: "Various Rishis",
    description: "Complete translation of all four Vedas with detailed scholarly commentary.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/vedas-complete-set/",
    price: 4500,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedas",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  },
  {
    id: "vb-002",
    title: "Rig Veda Samhita",
    author: "H.H. Wilson (translator)",
    description: "The oldest of the Vedas containing hymns to the cosmic deities.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/rig-veda/",
    price: 1200,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedas",
    imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=400&fit=crop",
  },
  {
    id: "vb-003",
    title: "Sama Veda: The Veda of Melodies",
    author: "Ralph T.H. Griffith (translator)",
    description: "The Veda of sacred chants used in rituals and meditation.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/sama-veda/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedas",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&h=400&fit=crop",
  },
  {
    id: "vb-004",
    title: "Atharva Veda: Hymns and Incantations",
    author: "Devi Chand (translator)",
    description: "The Veda containing knowledge of daily life, healing, and mystic practices.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/atharva-veda/",
    price: 950,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vedas",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "vb-005",
    title: "Brihadaranyaka Upanishad with Shankara Bhashya",
    author: "Shankaracharya",
    description: "The largest Upanishad with Shankaracharya's authoritative commentary.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/brihadaranyaka/",
    price: 750,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },
  {
    id: "vb-006",
    title: "Chandogya Upanishad",
    author: "Swami Gambhirananda (translator)",
    description: "One of the oldest Upanishads covering meditation, cosmology, and the nature of Self.",
    source: "vedic_books",
    sourceUrl: "https://www.vedicbooks.net/chandogya/",
    price: 595,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },

  // ===== MLBD (Motilal Banarsidass) =====
  {
    id: "mlbd-001",
    title: "A History of Indian Philosophy (5 Volumes)",
    author: "Surendranath Dasgupta",
    description: "Monumental academic work covering all schools of Indian philosophical thought.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/history-indian-philosophy/",
    price: 3500,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Philosophy",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  },
  {
    id: "mlbd-002",
    title: "The Principal Upanishads",
    author: "S. Radhakrishnan",
    description: "Scholarly translation of major Upanishads by the philosopher-president of India.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/principal-upanishads/",
    price: 850,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Upanishads",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  },
  {
    id: "mlbd-003",
    title: "Vaisesika Sutras of Kanada",
    author: "Nandalal Sinha (translator)",
    description: "Foundational text of Vaisheshika philosophy on atomic theory and categories of reality.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/vaisesika-sutras/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Vaisheshika",
    imageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=400&fit=crop",
  },
  {
    id: "mlbd-004",
    title: "Mimamsa Sutras of Jaimini",
    author: "Mohan Lal Sandal (translator)",
    description: "Core text of Purva Mimamsa philosophy on Vedic ritual and interpretation.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/mimamsa-sutras/",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Mimamsa",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
  },
  {
    id: "mlbd-005",
    title: "Natyashastra of Bharatamuni",
    author: "Bharatamuni",
    description: "Ancient treatise on dramaturgy, dance, and music with spiritual dimensions.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/natyashastra/",
    price: 1250,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Arts",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=300&h=400&fit=crop",
  },
  {
    id: "mlbd-006",
    title: "Arthashastra of Kautilya",
    author: "Kautilya (Chanakya)",
    description: "Ancient treatise on statecraft, economics, and political philosophy.",
    source: "mlbd",
    sourceUrl: "https://www.mlbd.com/arthashastra/",
    price: 695,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Philosophy",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=400&fit=crop",
  },

  // ===== BOOKISH SANTA =====
  {
    id: "bs-001",
    title: "The Serpent Power (Kundalini)",
    author: "Arthur Avalon (Sir John Woodroffe)",
    description: "Classic study of kundalini yoga and the chakra system from Tantric perspective.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/serpent-power/",
    price: 595,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  },
  {
    id: "bs-002",
    title: "Shakti and Shakta",
    author: "Arthur Avalon",
    description: "Comprehensive study of Shakta philosophy and goddess worship traditions.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/shakti-shakta/",
    price: 550,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Shakti",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  },
  {
    id: "bs-003",
    title: "Saundarya Lahari",
    author: "Shankaracharya",
    description: "Hundred verses in praise of the Divine Mother with tantric symbolism.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/saundarya-lahari/",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Shakti",
    imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=400&fit=crop",
  },
  {
    id: "bs-004",
    title: "Tantric Yoga and the Wisdom Goddesses",
    author: "David Frawley",
    description: "Exploration of the ten wisdom goddesses (Mahavidyas) in Tantric tradition.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/wisdom-goddesses/",
    price: 475,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&h=400&fit=crop",
  },
  {
    id: "bs-005",
    title: "Kashmir Shaivism: The Secret Supreme",
    author: "Swami Lakshman Joo",
    description: "Authoritative exposition of non-dual Shaiva philosophy from Kashmir.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/kashmir-shaivism/",
    price: 525,
    currency: "INR",
    isAvailable: true,
    language: "English",
    category: "Shaivism",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  },
  {
    id: "bs-006",
    title: "Spanda Karikas: The Divine Creative Pulsation",
    author: "Jaideva Singh",
    description: "Key text of Kashmir Shaivism on the vibrating nature of consciousness.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/spanda-karikas/",
    price: 425,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Shaivism",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop",
  },
  {
    id: "bs-007",
    title: "Pratyabhijnahrdayam: The Secret of Self-Recognition",
    author: "Kshemaraja",
    description: "Essential text of Recognition philosophy from Kashmir Shaivism.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/pratyabhijnahrdayam/",
    price: 395,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Shaivism",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=300&h=400&fit=crop",
  },
  {
    id: "bs-008",
    title: "Vijnanabhairava: Divine Consciousness",
    author: "Jaideva Singh",
    description: "112 meditation techniques from the dialogue between Shiva and Devi.",
    source: "bookish_santa",
    sourceUrl: "https://www.bookishsanta.com/vijnanabhairava/",
    price: 450,
    currency: "INR",
    isAvailable: true,
    language: "Sanskrit-English",
    category: "Tantra",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  },
];
